#!/bin/sh

CA_ROOT=ca-root
DAYS=999999

CLI_BASE=1000
CLI_AMT=$CLIENT_GEN
SRV_BASE=0
SRV_AMT=10

CLI_PREFIX=cli
SRV_PREFIX=srv

EXT_PREFIX=/tmp/.ca_ext.

updatecwd() {
    cd "$(dirname $0)"
}

output_ext_file() {
    cat << EOF >${EXT_PREFIX}${1}
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = $1
EOF
    echo ${EXT_PREFIX}${1}
}

gencert() {
    echo Generating certificate $target
    mkdir $targetdir
    openssl genrsa -out $targetdir/key 2048
    openssl req -new -subj "/CN=${target}" -sha256 -key $targetdir/key -nodes \
        -out $targetdir/csr
    openssl x509 -req -in $targetdir/csr -CA $CA_ROOT/crt -CAkey $CA_ROOT/key -CAcreateserial \
        -out $targetdir/crt -days $DAYS -sha256 -extfile $(output_ext_file $target)
    rm $targetdir/csr
    cat $targetdir/crt $CA_ROOT/crt > $targetdir/chain
}

regenerate() {
    echo Removing old CA
    rm -rf $CA_ROOT
    mkdir $CA_ROOT

    echo Generating new root key
    openssl genrsa -out $CA_ROOT/key 2048

    echo Generating new root certificate
    openssl req -new -x509 -subj "/CN=localhost" -sha256 -key $CA_ROOT/key -nodes \
        -days $DAYS -out $CA_ROOT/crt

    for kind in $SRV_PREFIX $CLI_PREFIX; do
        case $kind in
            $SRV_PREFIX)
                prefix=$SRV_PREFIX
                base=$SRV_BASE
                amt=$SRV_AMT
                ;;
            $CLI_PREFIX)
                prefix=$CLI_PREFIX
                base=$CLI_BASE
                amt=$CLI_AMT
                ;;
            *)
                echo Fatal error: Invalid node prefix.
                exit 1
                ;;
        esac

        for i in `seq 0 $(expr $amt - 1)`; do
            target=${prefix}$(expr $base + $i)
            targetdir=${CA_ROOT}/${target}

            gencert 2>/dev/null
        done
    done

    rm ${EXT_PREFIX}*
}

main() {
    updatecwd

    regenerate
}

main
