#!/bin/sh

cargo_do() {
    export RUSTFLAGS="-C target-cpu=native"
    subcmd=$1
    shift
    exec cargo +nightly $subcmd --features expose_impl $@
}

case $1 in
    clean)
        rm -rf target/
        ;;
    build|test|bench|doc|run)
        cargo_do $@
        ;;
    *)
        echo Usage: $0 "<build|test|bench|doc|run|clean>"
        exit 1
esac
