/// Replica will get the 5XX metrics codes
pub const ORDERING_PROTOCOL_POLL_TIME: &str = "ORDERING_PROTOCOL_POLL_TIME";
pub const ORDERING_PROTOCOL_POLL_TIME_ID: usize = 500;

pub const ORDERING_PROTOCOL_PROCESS_TIME: &str = "ORDERING_PROTOCOL_PROCESS_TIME";
pub const ORDERING_PROTOCOL_PROCESS_TIME_ID: usize = 501;

pub const STATE_TRANSFER_PROCESS_TIME: &str = "STATE_TRANSFER_PROCESS_TIME";
pub const STATE_TRANSFER_PROCESS_TIME_ID: usize = 502;